include: package:very_good_analysis/analysis_options.3.1.0.yaml

analyzer:
  exclude:
    - test/**.mocks.dart
    - lib/data/models/**.dart

linter:
  rules:
    public_member_api_docs: false
    cascade_invocations: false
    avoid_dynamic_calls: false
    one_member_abstracts: false
